# Generated by Django 5.2 on 2026-01-25 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('tools', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('github', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Project_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('content', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='showcase.project')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('project', 'slug')},
            },
        ),
    ]
