# Generated by Django 5.2 on 2026-01-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_section',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
