# Generated by Django 5.2 on 2025-04-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showcase", "0002_alter_project_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(default="", upload_to="project_images/"),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="ProjectImage",
        ),
    ]
