# Generated by Django 5.2 on 2025-04-06 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("showcase", "0003_project_image_delete_projectimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="image",
        ),
    ]
